---
title: "Homework # 9"
author: "Elliott Pryor"
date: "10/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 4, fig.height = 4)
```

\renewcommand{\sp}{\; \;}
\newcommand*\Eval[3]{\left.#1\right\rvert_{#2}^{#3}}

# Problem 1
## Statement

The random variables $X$ and $Y$ have the joint distribution $f_{X, Y}$ given by:

$$f_{X,Y} (x,y) = \begin{cases}
\frac{1}{y! \, \Gamma(\theta) \delta^\theta} x^{y + \theta - 1} e^{-x \left(\frac{1}{\delta} + 1 \right)} & \text{if } y = 0,1,2,... \sp 0 < x < \infty\\
0 & \text{otherwise}
\end{cases}$$

Where: $\delta, \theta > 0$

a. Calculate the marginal pdf $f_X(x)$. Identify this distribution and its parameter(s).

b. Calculate the marginal pmf $f_Y(y)$

\hrule
## Solution

a. We have to sum over the support of $Y$ so 
\begin{align*}
f_X(x) &= \sum_{y = 0}^\infty \frac{1}{y! \, \Gamma(\theta) \delta^\theta} x^{y + \theta - 1} e^{-x \left(\frac{1}{\delta} + 1 \right)}\\
&= f_X(x) = \frac{e^{-x \left( \frac{1}{\delta}\right) }  x^{\theta - 1}}{\Gamma(\theta) \delta^\theta} \sum_{y = 0}^\infty \frac{1}{y!} e^{-x} x^{y} \quad \implies Y \sim Poisson(\lambda = x)\\
&= = f_X(x) = \frac{e^{-x \left( \frac{1}{\delta} \right) }  x^{\theta - 1}}{\Gamma(\theta) \delta^\theta} I_{(0, \infty)(x)}
\end{align*}
$f_X(x)$ follows a gamma distribution with $\alpha = \theta$ and $\beta = \delta$


b. We integrate out the support of $X$ so:
 We have to sum over the support of $Y$ so 
\begin{align*}
f_Y(y) &= \int_0^\infty \frac{1}{y! \, \Gamma(\theta) \delta^\theta} x^{y + \theta - 1} e^{-x \left(\frac{1}{\delta} + 1 \right)} dx \\
&=  \frac{1}{y!} \int_0^\infty \frac{1}{\Gamma(\theta) \delta^\theta} x^{y} x^{\theta - 1} e^{-x/ \delta} e^{-x} dx\\
&= \frac{1}{y!} \left( \int_0^\infty x^{y} e^{-x} dx\right) \left( \int_0^\infty \frac{1}{\Gamma(\theta) \delta^\theta}  x^{\theta - 1} e^{-x/ \delta} dx \right) \quad \implies X \sim Gamma(\alpha = \theta, \beta = \delta)\\
&= \frac{1}{y!} \left(\int_0^\infty x^{y} e^{-x} dx\right) \\
&= \frac{1}{y!} \Gamma(y +1) \quad y \in \mathbb{N} \cup \{0\}
\end{align*}
*I feel like this should simplify more, using the *
$\Gamma(y + 1)$
*and somehow using the beta distribution. But I can't figure out how since* $\alpha = y$ $\beta = 1$ *doesn't work*

# Problem 2
## Statement

Find $P(X > \sqrt{Y}$ if $X$, $Y$ are jointly distributed with pdf:
$$f_{X,Y}(x,y) = x+y \quad 0\leq x \leq 1 , \sp 0 \leq y \leq 1$$

\hrule
## Solution


We need a 2D integral. We also know that $X, Y$ are continuous so we can substitute $P(X \geq \sqrt{Y})$

$$\int_0^1 \int_{\sqrt{y}}^1 (x + y) dx dy$$
\begin{align*}
P(X \geq \sqrt{Y}) &= \int_0^1 \int_{\sqrt{y}}^1 (x + y) dx dy \\
&= \int_0^1 \Eval{1/2 x^2 + xy}{\sqrt{y}}{1} dy\\
&= \int_0^1 (1/2 y + y^{3/2}) dy\\
&= \Eval{1/4 y^4 + 2/5 y^{5/2}}{0}{1}\\
&= 1/4 + 2/5 - 0 - 0\\
&= 13/20
\end{align*}





# Problem 3
## Statement

Find $P(X^2 < Y < X)$ if $X$, $Y$, are jointly distributed with pdf 
$$f_{X,Y}(x,y) = 2x \quad 0\leq x \leq 1 , \sp 0 \leq y \leq 1$$

\hrule
## Solution



\begin{align*}
P(X \geq \sqrt{Y}) &= \int_0^1 \int_{x^2}^x (2x) dy dx \\
&= \int_0^1 \Eval{2xy}{x^2}{x} dx\\
&= \int_0^1 (2x^2 - 2x^3) dx\\
&= \Eval{2/3 x^3 -1/2 x^4}{0}{1}\\
&= 1/6
\end{align*}




# Problem 4
## Statement

A pdf is defined by

$$f_{X,Y} (x,y) = \begin{cases}
C(x + 2y) & \text{if } 0 < y < 1 \sp 0 < x < 2\\
0 & \text{otherwise}
\end{cases}$$

a. Find the value of C

b. Find the marginal pdf of X

c. Find the joint cdf of X and Y

\hrule
## Solution


a. C is the normalizing constant so it integrates to 1. 

\begin{align*}
1 &= C \int_0^1 \int_0^2 C (x + 2y) dx dy\\
1 &= C \int_0^1 \Eval{1/2x^2 + 2xy}{0}{2} dy\\
1 &= C \int_0^1 (2 + 4y) dy\\
1 &= C \Eval{2y + 2 y^2}{0}{1}\\
1 &= C (4)\\
1/4 &= C
\end{align*}

b. This was poor planning. I found marginal pdf of Y in part A.

\begin{align*}
f_X(x) &= C \int_0^1 C (x + 2y) dy\\
f_X(x) &= C \Eval{xy + y^2}{0}{1}\\
f_X(x) &= 1/4  (x+1) I_{(0,2)}(x)\\
\end{align*}



c. This was pretty much done in part a, but needs to be done generically.

\begin{align*}
F_{X,Y}(x,y) &= 1/4 \int \int  (x + 2y) dx dy\\
F_{X,Y}(x,y) &=  1/4 \int 1/2x^2 + 2xy dy\\
F_{X,Y}(x,y) &=  1/4 (1/2 x^2 y + y^2 x)\\
\end{align*}

We also need the marginal for Y:

\begin{align*}
f_Y(y) &= C \int_0^2 C (x + 2y) dx\\
f_Y(y) &= C \Eval{1/2 x^2 + 2xy}{0}{2}\\
f_Y(y) &= 1/4  (2+4y) I_{(0,1)}(y)\\
\end{align*}

$$F_{X,Y}(x,y) = \begin{cases}
1/4 (1/2 x^2 y + y^2 x) & 0 < y < 1, \sp 0 < x < 2\\
0 & y \leq 0, \sp x \leq 0\\
1 & y \geq 1, \sp x \geq 2\\
1/4(x + 1) & y \geq 1, \sp 0 < x < 2\\
1/4  (2+4y) & x \geq 2, \sp 0 < y < 1\\
\end{cases}$$

